name: Check Pull Requests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    name: Format, test, lint, check types
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn format:check && yarn test && yarn lint:check && yarn types:check
